import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Solvenix Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
  <div className="bg-gradient-to-r from-green-900 to-[#000000] min-h-screen overflow-y-auto overflow-x-hidden scrollbar-thin scrollbar-track-[#87ceeb] scrollbar-thumb-[#1e293b] scroll-smooth">


            <Navbar/>
             
        
             {children}
        </div>
     
      </body>
    </html>
  );
}
